import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto_Slab } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoSlab.variable} ${inter.variable} antialiased relative bg-black`}
      >
        {/* Top Left Gradient */}
        <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-[#0082F2] rounded-full mix-blend-screen filter blur-[150px] opacity-20 -z-10"></div>

        {/* Top Right Gradient */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-[#00358F] rounded-full mix-blend-screen filter blur-[150px] opacity-20 -z-10"></div>

        {/* Bottom Left Gradient */}
        <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-[#0082F2] rounded-full mix-blend-screen filter blur-[150px] opacity-20 -z-10"></div>

        {/* Middle Gradient */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#0082F2] rounded-full mix-blend-screen filter blur-[200px] opacity-15 -z-10"></div>

        {/* Bottom Right Gradient */}
        <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-[#00358F] rounded-full mix-blend-screen filter blur-[150px] opacity-20 -z-10"></div>


        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
