import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import circle from "@/assets/circle.png";
import circleRight from "@/assets/circle-right.png";
import ellipse from "@/assets/side.png";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoSlab.variable} ${inter.variable} antialiased relative bg-black`}
      >
        <Image
          className="absolute -z-[500]"
          src={circle}
          width={800}
          height={400}
          alt=""
        />
        {/* <Image
          className="absolute top-16"
          src={ellipse}
          width={800}
          height={400}
          alt=""
        /> */}
        {/* <Image
          className="absolute top-300"
          src={ellipse}
          width={800}
          height={400}
          alt=""
        /> */}
        <Image
          className="absolute right-0"
          src={circleRight}
          width={800}
          height={400}
          alt=""
        />

        {children}
      </body>
    </html>
  );
}
